import { Router, type IRouter } from "express";
import healthRouter from "./health";
import clinadminRouter from "./clinadmin";
import anthropicRouter from "./anthropic";
import deferralsRouter from "./deferrals";
import archivedRouter from "./archived";
import acknowledgedRouter from "./acknowledged";
import userTasksRouter from "./userTasks";
import linkedDocTasksRouter from "./linkedDocTasks";
import promptedTasksRouter from "./promptedTasks";
import sentLogRouter from "./sentLog";
import aiClassificationsRouter from "./aiClassifications";
import clinicianSettingsRouter from "./clinicianSettings";
import weeklyPlansRouter from "./weeklyPlans";
import manualTaskOverridesRouter from "./manualTaskOverrides";
import sidebarTasksRouter from "./sidebarTasks";
import evidenceSourcesRouter from "./evidenceSources";
import emailEvidenceRouter from "./emailEvidence";
import draftAuditRouter from "./draftAudit";
import chatAuditRouter from "./chatAudit";
import evidenceFetchRouter from "./evidenceFetch";
import leaveBlocksRouter from "./leaveBlocks";
import customFoldersRouter from "./customFolders";
import outlookFoldersRouter from "./outlookFolders";
import backlogItemsRouter from "./backlogItems";
import dismissedBacklogItemsRouter from "./dismissedBacklogItems";

const router: IRouter = Router();

router.use(healthRouter);
router.use(clinadminRouter);
router.use(anthropicRouter);
router.use(deferralsRouter);
router.use(archivedRouter);
router.use(acknowledgedRouter);
router.use(userTasksRouter);
router.use(linkedDocTasksRouter);
router.use(promptedTasksRouter);
router.use(sentLogRouter);
router.use(aiClassificationsRouter);
router.use(clinicianSettingsRouter);
router.use(weeklyPlansRouter);
router.use(manualTaskOverridesRouter);
router.use(sidebarTasksRouter);
router.use(evidenceSourcesRouter);
router.use(emailEvidenceRouter);
router.use(draftAuditRouter);
router.use(chatAuditRouter);
router.use(evidenceFetchRouter);
router.use(leaveBlocksRouter);
router.use(customFoldersRouter);
router.use(outlookFoldersRouter);
router.use(backlogItemsRouter);
router.use(dismissedBacklogItemsRouter);

export default router;
