// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-redesign/CalmClinical.tsx": () => import("../components/mockups/home-redesign/CalmClinical.tsx"),
  "./components/mockups/home-redesign/Current.tsx": () => import("../components/mockups/home-redesign/Current.tsx"),
  "./components/mockups/home-redesign/QuietEditorial.tsx": () => import("../components/mockups/home-redesign/QuietEditorial.tsx")
};
